// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1mtYe7pQYoc2Nm3AeEf8Y-J7oTKPsb4',
    appId: '1:411460404526:web:126cdaa8139132783b66bf',
    messagingSenderId: '411460404526',
    projectId: 'safe-hands-f0cb0',
    authDomain: 'safe-hands-f0cb0.firebaseapp.com',
    storageBucket: 'safe-hands-f0cb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphT5oaDvKaIkFFe_xMHBv51X_53AJYoU',
    appId: '1:411460404526:android:b96822bb0b9dd3be3b66bf',
    messagingSenderId: '411460404526',
    projectId: 'safe-hands-f0cb0',
    storageBucket: 'safe-hands-f0cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKL_Idep4wV3fVT8A6yiNcnu5ZcRwAz1g',
    appId: '1:411460404526:ios:6884322c44fdace13b66bf',
    messagingSenderId: '411460404526',
    projectId: 'safe-hands-f0cb0',
    storageBucket: 'safe-hands-f0cb0.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKL_Idep4wV3fVT8A6yiNcnu5ZcRwAz1g',
    appId: '1:411460404526:ios:6884322c44fdace13b66bf',
    messagingSenderId: '411460404526',
    projectId: 'safe-hands-f0cb0',
    storageBucket: 'safe-hands-f0cb0.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ1mtYe7pQYoc2Nm3AeEf8Y-J7oTKPsb4',
    appId: '1:411460404526:web:474c4935cd1aa1143b66bf',
    messagingSenderId: '411460404526',
    projectId: 'safe-hands-f0cb0',
    authDomain: 'safe-hands-f0cb0.firebaseapp.com',
    storageBucket: 'safe-hands-f0cb0.firebasestorage.app',
  );
}
